### PR TITLE
Create Min and Max for Credit and Debit

### LINKED ISSUE #9: Create Min and Max Debit Credit
**Is your feature request related to a problem? Please describe.**
In the overview section it only shows the total credit and debit, I think there is still something missing

**Describe the solution you'd like**
Can i create Pull Request to find Min and Max Credit and Debit in 'Total Field' ? This can make it easier for users to find out what the largest credit or smallest debit is

Screenshot_1633151792

### PR DESCRIPTION
**Pull request by yusriltakeuchi**
Hi @himanshusingh335 !

I create a feature to find min and max value for credit and debit, i show this in the summary field in overview screen. Not just that, i'm doing another task. This is what i do:
- Create min and max feature in Credit and Debit
- Refactoring Card into single Card Item (Reusable)
- Refresh state after Add item

Screenshot_1633178872

I hope you will merge this PR and labeled as hacktoberfest-accepted
Thank you :)

### CODE REVIEW

**Comment by himanshusingh335** [comment]
The min and max debit/credit shown is for the entire transaction history, correct ?

**Review by himanshusingh335 — APPROVED** [review]
Approved.

**Comment by himanshusingh335** [comment]
Just keep in mind, I had used provider state management for this project.

So in the Home_screen.dart, instead of making the class `HomeScreen` a `StatefulWidget`, you could have just added the line 'updateBalance = Provider.of<DatabaseServices>(context);' inside the build function to update data whenever any new change is made.

I believe i had forgotten to add that line while making the app and did not notice the stale data being shown in the Home Screen

**Comment by yusriltakeuchi** [comment]
> The min and max debit/credit shown is for the entire transaction history, correct ?

Yes, i find the value from the history

**Comment by yusriltakeuchi** [comment]
> Just keep in mind, I had used provider state management for this project.
> 
> So in the Home_Screen.dart, instead of making the class `HomeScreen` a `StatefulWidget`, you could have just added the line `updateBalance= Provider.of<DatabaseServices>(context);` inside the `build` function to update data whenever any new change is made.
> 
> I believe i had forgotten to add that line while making the app and did not notice the stale data being shown in the Home Screen

The reason why i change to Statefull because i found some problem.
When you add new item, the state of your item is not refreshed until i run hot reload.
So that's why i put this code after navigation

```dart
Navigator.pushNamed(context, '/new').then((value) {
  setState(() {});
});
```
That mean after you complete create new item, it will refresh current state, and the item is changes

**Pull request merged**
